{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uxrate",
    "module": "uxrate-sdk",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "uxrate-sdk-0.3.1.aar",
          "url": "uxrate-sdk-0.3.1.aar",
          "size": 288192,
          "sha512": "890c6bb819021e7369899530ca730ad3f65c7842c914ff14f8dc01ab33495b938e31f1bc4e956af7f25fed7bc3b3f379291cf81a59bb71aad1bd42c0c4d4ed0d",
          "sha256": "926496c6091b51e7a7dc27950f68d1f26edc7de467b44b3404cabbc4d66015d1",
          "sha1": "c0f5ee0a69eacfff8396765e58b803bd45591ec2",
          "md5": "00928145f7692545ba5ed3abc998af57"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "uxrate-sdk-0.3.1.aar",
          "url": "uxrate-sdk-0.3.1.aar",
          "size": 288192,
          "sha512": "890c6bb819021e7369899530ca730ad3f65c7842c914ff14f8dc01ab33495b938e31f1bc4e956af7f25fed7bc3b3f379291cf81a59bb71aad1bd42c0c4d4ed0d",
          "sha256": "926496c6091b51e7a7dc27950f68d1f26edc7de467b44b3404cabbc4d66015d1",
          "sha1": "c0f5ee0a69eacfff8396765e58b803bd45591ec2",
          "md5": "00928145f7692545ba5ed3abc998af57"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uxrate-sdk-0.3.1-sources.jar",
          "url": "uxrate-sdk-0.3.1-sources.jar",
          "size": 125293,
          "sha512": "18e2acee71ec3635a56837f28402d74c620bffce62c90ffda5bbcc5ddcfb67443437a1b7f92d0f00ef7cc7c1c6389a1300883514142075930b707c31b5c9dcde",
          "sha256": "e2a6dffaa0a27d0268b0adbd80b1b6ebbee02f71361e0f8c6004af88937a8e84",
          "sha1": "0aad2eff1cbb376e98f9f51016bab984bb3e0472",
          "md5": "bb0a55f32b644ed8b619ea6d300c0913"
        }
      ]
    }
  ]
}
