{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uxrate",
    "module": "uxrate-sdk",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "uxrate-sdk-0.3.2.aar",
          "url": "uxrate-sdk-0.3.2.aar",
          "size": 292905,
          "sha512": "d102d0608bcb24865bd792d441ca3d07d18ba522c7df29768d60b52c8552eee753640be08cca7bee30d44d877794497150c13270beb35043048809a0eb036362",
          "sha256": "9d58d6634a68eac99213ed4b6a9c1face09b7d40eb5a3d77c12e591338d98b92",
          "sha1": "67daa35a729f79b6990c92f1cd6b225f8ab71a3d",
          "md5": "5e798da056f9d1333e0c8eeed4b67ccd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "uxrate-sdk-0.3.2.aar",
          "url": "uxrate-sdk-0.3.2.aar",
          "size": 292905,
          "sha512": "d102d0608bcb24865bd792d441ca3d07d18ba522c7df29768d60b52c8552eee753640be08cca7bee30d44d877794497150c13270beb35043048809a0eb036362",
          "sha256": "9d58d6634a68eac99213ed4b6a9c1face09b7d40eb5a3d77c12e591338d98b92",
          "sha1": "67daa35a729f79b6990c92f1cd6b225f8ab71a3d",
          "md5": "5e798da056f9d1333e0c8eeed4b67ccd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uxrate-sdk-0.3.2-sources.jar",
          "url": "uxrate-sdk-0.3.2-sources.jar",
          "size": 127546,
          "sha512": "c5008b142920f3e00c86360cdc2a6485435cf0b57e3621c60d4f56089abb37b5f8cceb5c697f2656d0d979c59ab1b91bddaacc398ed04474c72b5be32a3b988b",
          "sha256": "1870123c061c0cdba8bc765590f6d04aa1fe9b8330ec19f96d2c66cb4269004e",
          "sha1": "75547726c0d53599431daf1dc3fca81a1f821b03",
          "md5": "73a6dcaec1f8c23d77229840a16555c3"
        }
      ]
    }
  ]
}
