{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uxrate",
    "module": "uxrate-sdk",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "uxrate-sdk-0.8.2.aar",
          "url": "uxrate-sdk-0.8.2.aar",
          "size": 361430,
          "sha512": "f80431a2fe1c1543077ca323f3c9bfc53a82cef60ccf8e7ddd843d1516e887ee3bf2dc29662907eec64ce20eef3ce12b76c119651c382ff30ad70ada79e555fc",
          "sha256": "67d9019a229006eb6790a6c7412047ccc60fa6e31edfd06adc7fd1fb0186b246",
          "sha1": "65ed0fc0f164c3a6d770bf9898a262abfac84202",
          "md5": "33a93e3efd380dfc62f06ba2bbcd55fb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "uxrate-sdk-0.8.2.aar",
          "url": "uxrate-sdk-0.8.2.aar",
          "size": 361430,
          "sha512": "f80431a2fe1c1543077ca323f3c9bfc53a82cef60ccf8e7ddd843d1516e887ee3bf2dc29662907eec64ce20eef3ce12b76c119651c382ff30ad70ada79e555fc",
          "sha256": "67d9019a229006eb6790a6c7412047ccc60fa6e31edfd06adc7fd1fb0186b246",
          "sha1": "65ed0fc0f164c3a6d770bf9898a262abfac84202",
          "md5": "33a93e3efd380dfc62f06ba2bbcd55fb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uxrate-sdk-0.8.2-sources.jar",
          "url": "uxrate-sdk-0.8.2-sources.jar",
          "size": 159544,
          "sha512": "4571ace57cb30f94f865de1cb9f5234c8235b4760b040495d23d930d240403c629eee71418a345350671b43a4fbe0d902726ed91b73a11d3a46dd0793fb07204",
          "sha256": "d13fe039573da510316e5887f292db85ac8252b9131687ce0bbe70cd508219c8",
          "sha1": "06ebd55860f92d6666bae1372c7947199932d637",
          "md5": "2ff8b49507d210170c04b44ee824cf35"
        }
      ]
    }
  ]
}
